### ISSUE TITLE
Please specify the official solution too.

### ISSUE THREAD

**Issue by t184256** [BobVul/Scaleway-Custom-Kernel-Launcher#1]
Hello. Your project is easily googleable directly or via blog posts, but now there's an official way of booting custom kernels on Scaleway: [tags KEXEC_KERNEL and KEXEC_INITRD](https://github.com/scaleway/initrd/tree/master/Linux#boot-options). If you could correct your outdated README.md and link to them that'd be great.
Thank you!

**Comment by BobVul** [comment]
Yea, I think that existed first but no one really talked about it. I've actually recommended the tags method in a couple of forum posts. 

I'll update the readme to point there when I get back to a computer.

**Comment by BobVul** [comment]
Kept the rest of it in case someone is still using this.

**Comment by t184256** [comment]
Sure, could be useful for other hosters!
